{{- range .Values.volumes }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "nfs-create-folder--{{ .name }}--release-{{ $.Release.Name }}"
  namespace: {{ $.Release.Namespace }}
spec:
  template:
    spec:
      containers:
      - name: create-nfs-folder
        image: bash
        {{- $trimmedPath := (trimPrefix "/" .path) }}
        command: ["mkdir", "--parents", "--verbose", {{ printf "/existing-path/%s" $trimmedPath | quote}} ]
        volumeMounts:
          - mountPath: "/existing-path"
            name: existing-path
      restartPolicy: Never
      volumes:
        - name: existing-path
          persistentVolumeClaim:
            claimName: {{ .name | quote }}
  backoffLimit: 4
{{- end }}
